---
# tasks file for package.apache
- name: install apache on deb
  apt:
    name: "{{apache_package_deb}}"
    state: present
  when: ansible_os_family == "Debain"
- name: install httpd on rhel
  yum:
    name: "{{apache_package_rhel}}"
    state: present
  when: anisble_os_family == "RedHat"
- name: sett service name for debain
  set_fact:
    apache-package: "{{apache_package_deb}}"
  when: ansible_os_family == "Debain"
- name: set service name for rhel
  set_fact:
    apache-package: "{{apache_package_rhel}}"
  when: ansible_os_family == "RedHat"
- name: start the service and enable
  service:
    name: "{{apache-package}}"
    enabled: yes
    state: started
- name: test to print
  debug:
    msg: firing notification for RedHat
  notify: restart  rhel apache
  when: ansible_os_family == "RedHat"
- name: tetst to print
  debug:
    msg:  firinig notification for Debian
  notify: restart debian apache
  when: ansible_os__family == "Debain"
                   

  